#配置文件
# room config
window_title: '雷电模拟器-1'
platform: 'wpk'
max_players: 8
big_blind: 20
small_blind: 10

# 配置文件路径
# room.yaml
config_path: 
  - 'config'
# room_template
template_path: 
  - 'config'
  - 'template'

# button 设置
bet1_power: 0.3
bet2_power: 0.5
bet3_power: 0.75
bet4_power: 1
bet5_power: 1.4

# solver config
version: '1.0'

# 策略与决策相关
# 文件路径