P0_dealer: !!python/tuple
- 192
- 804
- 215
- 825
P0_decision: !!python/tuple
- 235
- 693
- 313
- 710
P0_funds: !!python/tuple
- 236
- 951
- 305
- 976
P0_have_cards: !!python/tuple
- 214
- 828
- 331
- 909
P0_photo: !!python/tuple
- 248
- 725
- 284
- 743
P0_pot: !!python/tuple
- 315
- 751
- 374
- 776
P1_dealer: !!python/tuple
- 96
- 639
- 119
- 661
P1_decision: !!python/tuple
- 21
- 533
- 87
- 555
P1_funds: !!python/tuple
- 20
- 638
- 81
- 662
P1_have_cards: !!python/tuple
- 14
- 605
- 35
- 629
P1_photo: !!python/tuple
- 29
- 583
- 79
- 611
P1_pot: !!python/tuple
- 93
- 592
- 153
- 615
P2_dealer: !!python/tuple
- 93
- 474
- 122
- 500
P2_decision: !!python/tuple
- 22
- 369
- 85
- 392
P2_funds: !!python/tuple
- 18
- 475
- 87
- 500
P2_have_cards: !!python/tuple
- 12
- 443
- 37
- 465
P2_photo: !!python/tuple
- 29
- 421
- 79
- 447
P2_pot: !!python/tuple
- 92
- 428
- 157
- 453
P3_dealer: !!python/tuple
- 94
- 313
- 119
- 334
P3_decision: !!python/tuple
- 24
- 206
- 83
- 230
P3_funds: !!python/tuple
- 18
- 312
- 86
- 337
P3_have_cards: !!python/tuple
- 13
- 280
- 35
- 301
P3_photo: !!python/tuple
- 27
- 259
- 80
- 283
P3_pot: !!python/tuple
- 94
- 264
- 153
- 291
P4_dealer: !!python/tuple
- 314
- 221
- 341
- 244
P4_decision: !!python/tuple
- 240
- 115
- 302
- 138
P4_funds: !!python/tuple
- 236
- 221
- 306
- 245
P4_have_cards: !!python/tuple
- 289
- 189
- 309
- 211
P4_photo: !!python/tuple
- 246
- 166
- 293
- 194
P4_pot: !!python/tuple
- 233
- 273
- 307
- 294
P5_dealer: !!python/tuple
- 421
- 311
- 447
- 336
P5_decision: !!python/tuple
- 455
- 206
- 519
- 230
P5_funds: !!python/tuple
- 456
- 312
- 525
- 338
P5_have_cards: !!python/tuple
- 508
- 280
- 528
- 302
P5_photo: !!python/tuple
- 463
- 252
- 513
- 285
P5_pot: !!python/tuple
- 382
- 267
- 445
- 290
P6_dealer: !!python/tuple
- 420
- 476
- 446
- 499
P6_decision: !!python/tuple
- 455
- 369
- 525
- 392
P6_funds: !!python/tuple
- 456
- 475
- 523
- 499
P6_have_cards: !!python/tuple
- 507
- 443
- 528
- 465
P6_photo: !!python/tuple
- 462
- 412
- 513
- 447
P6_pot: !!python/tuple
- 382
- 428
- 448
- 451
P7_dealer: !!python/tuple
- 421
- 637
- 447
- 662
P7_decision: !!python/tuple
- 458
- 532
- 519
- 555
P7_funds: !!python/tuple
- 457
- 639
- 523
- 662
P7_have_cards: !!python/tuple
- 507
- 606
- 527
- 628
P7_photo: !!python/tuple
- 467
- 579
- 511
- 610
P7_pot: !!python/tuple
- 377
- 593
- 445
- 614
Player_buyin: !!python/tuple
- 418
- 77
- 466
- 127
Player_id: !!python/tuple
- 176
- 426
- 334
- 467
bet1: !!python/tuple
- 88
- 678
- 139
- 708
bet1_power: 0.3
bet2: !!python/tuple
- 168
- 641
- 218
- 666
bet2_power: 0.5
bet3: !!python/tuple
- 244
- 636
- 296
- 662
bet3_power: 0.75
bet4: !!python/tuple
- 321
- 639
- 374
- 668
bet4_power: 1
bet5: !!python/tuple
- 398
- 678
- 452
- 706
bet5_power: 1.4
board1_rank: !!python/tuple
- 121
- 461
- 150
- 501
board1_suit: !!python/tuple
- 140
- 511
- 171
- 534
board2_rank: !!python/tuple
- 183
- 461
- 211
- 501
board2_suit: !!python/tuple
- 202
- 509
- 230
- 533
board3_rank: !!python/tuple
- 241
- 461
- 272
- 500
board3_suit: !!python/tuple
- 262
- 511
- 291
- 530
board4_rank: !!python/tuple
- 304
- 461
- 332
- 499
board4_suit: !!python/tuple
- 326
- 512
- 349
- 531
board5_rank: !!python/tuple
- 365
- 462
- 395
- 499
board5_suit: !!python/tuple
- 386
- 512
- 414
- 532
hero_bet: !!python/tuple
- 244
- 751
- 298
- 792
hero_call: !!python/tuple
- 364
- 791
- 432
- 836
hero_card1_rank: !!python/tuple
- 210
- 828
- 238
- 867
hero_card1_suit: !!python/tuple
- 227
- 869
- 264
- 894
hero_card2_rank: !!python/tuple
- 274
- 828
- 301
- 865
hero_card2_suit: !!python/tuple
- 289
- 875
- 328
- 896
hero_fold: !!python/tuple
- 119
- 785
- 162
- 805
pot_last_round: !!python/tuple
- 249
- 326
- 314
- 349
pot_total: !!python/tuple
- 229
- 295
- 313
- 318
